# Generated by Django 4.0.4 on 2022-06-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='id_card',
            field=models.IntegerField(),
        ),
    ]
