# Generated by Django 4.0.4 on 2022-06-05 23:37

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_favoritos_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='photo',
            field=models.ImageField(null=sqlalchemy.sql.expression.true, upload_to=''),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
