# Generated by Django 4.0.4 on 2022-06-06 12:28

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.TextField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
