# Generated by Django 4.0.4 on 2022-06-06 12:39

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.TimeField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
