# Generated by Django 4.0.4 on 2022-06-06 12:42

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.TextField(null=sqlalchemy.sql.expression.true),
        ),
    ]
