# Generated by Django 4.0.4 on 2022-06-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_remove_note_title_note_likesnuber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='likesNuber',
        ),
    ]
